### ISSUE TITLE
extended Latin symbols don't render

### ISSUE THREAD

**Issue by maxmerben** [agricolamz/lingglosses#21]
What I type:
```{r, echo=FALSE}
gloss_example(transliteration = "boʔ-ac’a-da",
              glosses = "four-ten-NUM",
              free_translation = "40"
)
```

What is rendered:
* _bo<U+0294>-ac’a-da_
four-ten-num
‘40’

Quite sad :(

<details> <summary> More examples: </summary>

```{r, echo=FALSE}
gloss_example(transliteration = "xːɵ-c’al-wa",
              glosses = "five-ten-NUM.III",
              free_translation = "50"
)
```
is rendered as:
* _x<U+02D0><U+0275>-c’al-wa_
five-ten-num.iii
‘50’

-----

```{r, echo=FALSE}
gloss_example(transliteration = "ša-uz-t’q’a-it’ː",   # IPA triangular colon instead of a regular one
              glosses = "two-MULT-twenty-ten",
              free_translation = "50"
)
```
is rendered as:
* _sa-uz-t’q’a-it’<U+02D0>_
two-mult-twenty-ten
‘50’

-----

</details>

<details> <summary> info about OS and package versions </summary>

```
> sessionInfo()$R.version$platform
[1] "x86_64-w64-mingw32"
> sessionInfo()$R.version$version.string
[1] "R version 4.1.1 (2021-08-10)"
> packageVersion("rmarkdown")
[1] ‘2.17’
> packageVersion("lingglosses")
[1] ‘0.0.4’
```

</details>

**Comment by agricolamz** [comment]
On Linux it looks good :( I'll ask around...

![image](https://user-images.githubusercontent.com/15956515/218316175-030c1015-6529-4690-a16a-20616416b3c8.png)
