### ISSUE TITLE
`knitr::opts_current` is supposed to be read-only

### ISSUE THREAD

**Issue by yihui** [agricolamz/lingglosses#22]
Hi, I'm not sure what this line is for:
https://github.com/agricolamz/lingglosses/blob/dde92942570c7f7acf4334a35cd70008511c8e80/R/make_gloss_list.R#L23

I think `knitr::asis_output()` should suffice:
https://github.com/agricolamz/lingglosses/blob/dde92942570c7f7acf4334a35cd70008511c8e80/R/make_gloss_list.R#L149

In the next version of **knitr**, `opts_chunk$set()` will throw an error: https://github.com/yihui/knitr/issues/1798 I wonder if you could delete that line if it's not necessary. Thank you very much!

BTW, it will also be nice if you run `R CMD check` on your package against the dev version of **knitr** in case I missed any other problems (I only discovered this one on my side).

**Comment by agricolamz** [comment]
@yihui, thank you, I will fix within the next week!
