### ISSUE TITLE
english check

### ISSUE THREAD

**Issue by agricolamz** [agricolamz/lingglosses#4]
- [tutorial](https://github.com/agricolamz/lingglosses/blob/master/docs/index.Rmd), [html version](https://agricolamz.github.io/lingglosses/)
- [Description](https://github.com/agricolamz/lingglosses/blob/master/DESCRIPTION)
- [NEWS](https://github.com/agricolamz/lingglosses/blob/master/NEWS.md)
- [Documentation](https://cran.r-project.org/web/packages/lingglosses/lingglosses.pdf). In order to correct it you need to change files in the R folder.

**Comment by sverhees** [comment]
Corrected all and created pull requests :)

**Comment by agricolamz** [comment]
Thanks!
